import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'ChitChatter | Login',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className='w-full h-full bg-gradient-to-r from-slate-900 via-slate-900/60 to-slate-900'>{children}</div>;
}
