import { TopBar } from '@/components/sections/top-bar';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'RocketChat',
  description: 'Generated by create next app',
};

export default function PageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className='relative w-full h-full flex flex-col items-center justify-center pt-20'>
      <TopBar />
      {children}
    </div>
  );
}
